---
- name: Check if Android Studio is already installed
  stat:
    path: "{{ install_dir }}/android-studio/bin/studio.sh"
  register: installed

- name: Download Android Studio
  get_url:
    url: "{{ download_url }}"
    dest: "/tmp/{{ zip_name }}"
    checksum: "{{ studio_checksum }}"
  when: not installed.stat.exists or force is defined

- name: Ensure install directory exists
  file:
    path: "{{ install_dir }}"
    state: directory
  when: not installed.stat.exists or force is defined

- name: Extract Android Studio
  unarchive:
    src: "/tmp/{{ zip_name }}"
    dest: "{{ install_dir }}"
    creates: "{{ install_dir }}/android-studio/bin/studio.sh"
  when: not installed.stat.exists or force is defined

- name: Add Android Studio to PATH
  blockinfile:
    marker: "# {mark} Android Studio Environment"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    content: |
      export PATH=$PATH:{{ install_dir }}/android-studio/bin
    backup: yes
